# Send prefix
set-option -g prefix C-space
unbind-key C-b
bind-key C-space send-prefix

#set-option -ga terminal-overrides ",xterm-256color:Tc"

# Winder numbering begins at 1 instead of 0
set -g base-index 1

#bind h select-pane -L
#bind k select-pane -U
#bind j select-pane -D
#bind l select-pane -R

# Use Alt_arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Mouse mode
setw -g mouse on

#set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

set -g status-bg green
set -g status-fg white
set -g status-left-length 20
set -g status-right-length 10

# As recommended by Neovim
set-option -sg escape-time 10 
set-option -g focus-events on
set-option -sa terminal-overrides ',xterm-256color:RGB'


